#!/usr/bin/env bash
if [[ $# -ne 2 ]]; then
    echo 'usage: change-commit-date COMMIT_HASH NEW_DATE';
    exit 1;
fi

COMMIT=$(git rev-parse --short $1)

{
    GIT_SEQUENCE_EDITOR="sed -i -e 's/^pick $COMMIT/e $COMMIT/'";
    GIT_COMMITER_DATE="$2";

    git rebase $COMMIT^ -i
    git commit --amend --no-edit --date "$GIT_COMMITER_DATE"
    git rebase --continue
}
